// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdzgWi90rmUwkTEl1QZIfw58c1fo7C44k',
    appId: '1:273582941106:web:c4a7f886ce4c7e661efaab',
    messagingSenderId: '273582941106',
    projectId: 'razorpay-6457d',
    authDomain: 'razorpay-6457d.firebaseapp.com',
    storageBucket: 'razorpay-6457d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9L0FfX5Sw2rW0_E7RptOKauClf3mH_rs',
    appId: '1:273582941106:android:f90aae7c7bfad0b71efaab',
    messagingSenderId: '273582941106',
    projectId: 'razorpay-6457d',
    storageBucket: 'razorpay-6457d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3U13xZR1xMBNtIeRU38aJxysdtDMY-kY',
    appId: '1:273582941106:ios:7e7ef7fd9bde29961efaab',
    messagingSenderId: '273582941106',
    projectId: 'razorpay-6457d',
    storageBucket: 'razorpay-6457d.appspot.com',
    iosBundleId: 'com.example.razorpay',
  );
}
